{"uid":"e3c36ff0b2f53a18","name":"test_issue_name_allure_dynamic_steps","fullName":"tests.test_issue_name#test_issue_name_allure_dynamic_steps","historyId":"915d88ccd72173549f0ed87b46290ef5","time":{"start":1697240685063,"stop":1697240685917,"duration":854},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5605b237afb3 <unknown>\n#1 0x5605b204e4a7 <unknown>\n#2 0x5605b2081c93 <unknown>\n#3 0x5605b207e10c <unknown>\n#4 0x5605b20c0ac6 <unknown>\n#5 0x5605b20b7713 <unknown>\n#6 0x5605b208a18b <unknown>\n#7 0x5605b208af7e <unknown>\n#8 0x5605b23408d8 <unknown>\n#9 0x5605b2344800 <unknown>\n#10 0x5605b234ecfc <unknown>\n#11 0x5605b2345418 <unknown>\n#12 0x5605b231242f <unknown>\n#13 0x5605b23694e8 <unknown>\n#14 0x5605b23696b4 <unknown>\n#15 0x5605b237a143 <unknown>\n#16 0x7f25df094b43 <unknown>","statusTrace":"def test_issue_name_allure_dynamic_steps():\n        allure.dynamic.tag('web')\n        allure.dynamic.severity(Severity.NORMAL)\n        allure.dynamic.label('owner', 'Y3ll0wman')\n        allure.dynamic.feature('Задачи в репозитории')\n        allure.dynamic.story('Название задачи отображается не зарегистрированному пользователю')\n        allure.dynamic.link('https://github.com/', name='Testing')\n    \n        with allure.step(\"Открыть github.com\"):\n>           browser.open('/')\n\ntests/test_issue_name.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py:1155: in open\n    self.config._executor.get_url(relative_or_absolute_url)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:301: in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:216: in get\n    driver = config.driver\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:343: in __get__\n    driver = config.build_driver_strategy(config)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:171: in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:93: in install_and_build_chrome\n    return Chrome(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:205: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:289: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f196eaa0dd0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: Chrome failed to sta...\\\\n#14 0x5605b23696b4 \\\\u003Cunknown>\\\\n#15 0x5605b237a143 \\\\u003Cunknown>\\\\n#16 0x7f25df094b43 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\nE         (session not created: DevToolsActivePort file doesn't exist)\nE         (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nE       Stacktrace:\nE       #0 0x5605b237afb3 <unknown>\nE       #1 0x5605b204e4a7 <unknown>\nE       #2 0x5605b2081c93 <unknown>\nE       #3 0x5605b207e10c <unknown>\nE       #4 0x5605b20c0ac6 <unknown>\nE       #5 0x5605b20b7713 <unknown>\nE       #6 0x5605b208a18b <unknown>\nE       #7 0x5605b208af7e <unknown>\nE       #8 0x5605b23408d8 <unknown>\nE       #9 0x5605b2344800 <unknown>\nE       #10 0x5605b234ecfc <unknown>\nE       #11 0x5605b2345418 <unknown>\nE       #12 0x5605b231242f <unknown>\nE       #13 0x5605b23694e8 <unknown>\nE       #14 0x5605b23696b4 <unknown>\nE       #15 0x5605b237a143 <unknown>\nE       #16 0x7f25df094b43 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"browser_management","time":{"start":1697240685062,"stop":1697240685062,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5605b237afb3 <unknown>\n#1 0x5605b204e4a7 <unknown>\n#2 0x5605b2081c93 <unknown>\n#3 0x5605b207e10c <unknown>\n#4 0x5605b20c0ac6 <unknown>\n#5 0x5605b20b7713 <unknown>\n#6 0x5605b208a18b <unknown>\n#7 0x5605b208af7e <unknown>\n#8 0x5605b23408d8 <unknown>\n#9 0x5605b2344800 <unknown>\n#10 0x5605b234ecfc <unknown>\n#11 0x5605b2345418 <unknown>\n#12 0x5605b231242f <unknown>\n#13 0x5605b23694e8 <unknown>\n#14 0x5605b23696b4 <unknown>\n#15 0x5605b237a143 <unknown>\n#16 0x7f25df094b43 <unknown>","statusTrace":"def test_issue_name_allure_dynamic_steps():\n        allure.dynamic.tag('web')\n        allure.dynamic.severity(Severity.NORMAL)\n        allure.dynamic.label('owner', 'Y3ll0wman')\n        allure.dynamic.feature('Задачи в репозитории')\n        allure.dynamic.story('Название задачи отображается не зарегистрированному пользователю')\n        allure.dynamic.link('https://github.com/', name='Testing')\n    \n        with allure.step(\"Открыть github.com\"):\n>           browser.open('/')\n\ntests/test_issue_name.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py:1155: in open\n    self.config._executor.get_url(relative_or_absolute_url)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:301: in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:216: in get\n    driver = config.driver\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:343: in __get__\n    driver = config.build_driver_strategy(config)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:171: in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:93: in install_and_build_chrome\n    return Chrome(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:205: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:289: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f196eaa0dd0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: Chrome failed to sta...\\\\n#14 0x5605b23696b4 \\\\u003Cunknown>\\\\n#15 0x5605b237a143 \\\\u003Cunknown>\\\\n#16 0x7f25df094b43 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\nE         (session not created: DevToolsActivePort file doesn't exist)\nE         (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nE       Stacktrace:\nE       #0 0x5605b237afb3 <unknown>\nE       #1 0x5605b204e4a7 <unknown>\nE       #2 0x5605b2081c93 <unknown>\nE       #3 0x5605b207e10c <unknown>\nE       #4 0x5605b20c0ac6 <unknown>\nE       #5 0x5605b20b7713 <unknown>\nE       #6 0x5605b208a18b <unknown>\nE       #7 0x5605b208af7e <unknown>\nE       #8 0x5605b23408d8 <unknown>\nE       #9 0x5605b2344800 <unknown>\nE       #10 0x5605b234ecfc <unknown>\nE       #11 0x5605b2345418 <unknown>\nE       #12 0x5605b231242f <unknown>\nE       #13 0x5605b23694e8 <unknown>\nE       #14 0x5605b23696b4 <unknown>\nE       #15 0x5605b237a143 <unknown>\nE       #16 0x7f25df094b43 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: SessionNotCreatedException","steps":[{"name":"Открыть github.com","time":{"start":1697240685063,"stop":1697240685916,"duration":853},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5605b237afb3 <unknown>\n#1 0x5605b204e4a7 <unknown>\n#2 0x5605b2081c93 <unknown>\n#3 0x5605b207e10c <unknown>\n#4 0x5605b20c0ac6 <unknown>\n#5 0x5605b20b7713 <unknown>\n#6 0x5605b208a18b <unknown>\n#7 0x5605b208af7e <unknown>\n#8 0x5605b23408d8 <unknown>\n#9 0x5605b2344800 <unknown>\n#10 0x5605b234ecfc <unknown>\n#11 0x5605b2345418 <unknown>\n#12 0x5605b231242f <unknown>\n#13 0x5605b23694e8 <unknown>\n#14 0x5605b23696b4 <unknown>\n#15 0x5605b237a143 <unknown>\n#16 0x7f25df094b43 <unknown>\n\n","statusTrace":"  File \"/home/runner/work/qa_guru_python_8_9/qa_guru_python_8_9/tests/test_issue_name.py\", line 25, in test_issue_name_allure_dynamic_steps\n    browser.open('/')\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py\", line 1155, in open\n    self.config._executor.get_url(relative_or_absolute_url)\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 301, in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 216, in get\n    driver = config.driver\n             ^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 343, in __get__\n    driver = config.build_driver_strategy(config)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 171, in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n           ^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 93, in install_and_build_chrome\n    return Chrome(\n           ^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 205, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 289, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[{"uid":"2568efcb833e23b1","name":"stderr","source":"2568efcb833e23b1.txt","type":"text/plain","size":516}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":1,"hasContent":true},"afterStages":[{"name":"browser_management::0","time":{"start":1697240685981,"stop":1697240686834,"duration":853},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55cc7db97fb3 <unknown>\n#1 0x55cc7d86b4a7 <unknown>\n#2 0x55cc7d89ec93 <unknown>\n#3 0x55cc7d89b10c <unknown>\n#4 0x55cc7d8ddac6 <unknown>\n#5 0x55cc7d8d4713 <unknown>\n#6 0x55cc7d8a718b <unknown>\n#7 0x55cc7d8a7f7e <unknown>\n#8 0x55cc7db5d8d8 <unknown>\n#9 0x55cc7db61800 <unknown>\n#10 0x55cc7db6bcfc <unknown>\n#11 0x55cc7db62418 <unknown>\n#12 0x55cc7db2f42f <unknown>\n#13 0x55cc7db864e8 <unknown>\n#14 0x55cc7db866b4 <unknown>\n#15 0x55cc7db97143 <unknown>\n#16 0x7f81e1294b43 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"/home/runner/work/qa_guru_python_8_9/qa_guru_python_8_9/tests/conftest.py\", line 13, in browser_management\n    browser.quit()\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py\", line 1205, in quit\n    self.driver.quit()\n    ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py\", line 1100, in driver\n    return self.config.driver\n           ^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 343, in __get__\n    driver = config.build_driver_strategy(config)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 171, in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n           ^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 93, in install_and_build_chrome\n    return Chrome(\n           ^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 205, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 289, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"labels":[{"name":"tag","value":"web"},{"name":"severity","value":"normal"},{"name":"owner","value":"Y3ll0wman"},{"name":"feature","value":"Задачи в репозитории"},{"name":"story","value":"Название задачи отображается не зарегистрированному пользователю"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_issue_name"},{"name":"host","value":"fv-az548-325"},{"name":"thread","value":"2434-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_issue_name"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[{"name":"Testing","url":"https://github.com/","type":"link"}],"hidden":false,"retry":false,"extra":{"severity":"normal","owner":"Y3ll0wman","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"c4082762c12ade1","reportUrl":"https://Y3ll0wman.github.io/qa_guru_python_8_9/8//#testresult/c4082762c12ade1","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55b34b124fb3 <unknown>\n#1 0x55b34adf84a7 <unknown>\n#2 0x55b34ae2bc93 <unknown>\n#3 0x55b34ae2810c <unknown>\n#4 0x55b34ae6aac6 <unknown>\n#5 0x55b34ae61713 <unknown>\n#6 0x55b34ae3418b <unknown>\n#7 0x55b34ae34f7e <unknown>\n#8 0x55b34b0ea8d8 <unknown>\n#9 0x55b34b0ee800 <unknown>\n#10 0x55b34b0f8cfc <unknown>\n#11 0x55b34b0ef418 <unknown>\n#12 0x55b34b0bc42f <unknown>\n#13 0x55b34b1134e8 <unknown>\n#14 0x55b34b1136b4 <unknown>\n#15 0x55b34b124143 <unknown>\n#16 0x7fec43494b43 <unknown>","time":{"start":1697240249286,"stop":1697240250231,"duration":945}},{"uid":"e44024ebd87c1230","reportUrl":"https://Y3ll0wman.github.io/qa_guru_python_8_9/7//#testresult/e44024ebd87c1230","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55b3f72fafb3 <unknown>\n#1 0x55b3f6fce4a7 <unknown>\n#2 0x55b3f7001c93 <unknown>\n#3 0x55b3f6ffe10c <unknown>\n#4 0x55b3f7040ac6 <unknown>\n#5 0x55b3f7037713 <unknown>\n#6 0x55b3f700a18b <unknown>\n#7 0x55b3f700af7e <unknown>\n#8 0x55b3f72c08d8 <unknown>\n#9 0x55b3f72c4800 <unknown>\n#10 0x55b3f72cecfc <unknown>\n#11 0x55b3f72c5418 <unknown>\n#12 0x55b3f729242f <unknown>\n#13 0x55b3f72e94e8 <unknown>\n#14 0x55b3f72e96b4 <unknown>\n#15 0x55b3f72fa143 <unknown>\n#16 0x7fe4aaa94b43 <unknown>","time":{"start":1697240090308,"stop":1697240091193,"duration":885}},{"uid":"447c8cb0ff5c6e64","reportUrl":"https://Y3ll0wman.github.io/qa_guru_python_8_9/6//#testresult/447c8cb0ff5c6e64","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x557fe23dcfb3 <unknown>\n#1 0x557fe20b04a7 <unknown>\n#2 0x557fe20e3c93 <unknown>\n#3 0x557fe20e010c <unknown>\n#4 0x557fe2122ac6 <unknown>\n#5 0x557fe2119713 <unknown>\n#6 0x557fe20ec18b <unknown>\n#7 0x557fe20ecf7e <unknown>\n#8 0x557fe23a28d8 <unknown>\n#9 0x557fe23a6800 <unknown>\n#10 0x557fe23b0cfc <unknown>\n#11 0x557fe23a7418 <unknown>\n#12 0x557fe237442f <unknown>\n#13 0x557fe23cb4e8 <unknown>\n#14 0x557fe23cb6b4 <unknown>\n#15 0x557fe23dc143 <unknown>\n#16 0x7f3a18e94b43 <unknown>","time":{"start":1697239880774,"stop":1697239881725,"duration":951}}]},"tags":["web"]},"source":"e3c36ff0b2f53a18.json","parameterValues":[]}